services:
  keycloak:
    image: bitnami/keycloak
    restart: always
    ports:
      - 8000:8080
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: dev
      KEYCLOAK_DATABASE_PASSWORD: dev
    networks:
      - dockernet

networks:
  dockernet:
    external: true

